### ISSUE TITLE
Send2Terminal option is disable

### ISSUE THREAD

**Issue by fsbsilva** [holgerbrandl/send2terminal#1]
Hey There,

I've installed this plugin and I was trying to use. However, I've followed your instruction but didn't work. 

I selected the line, clicked on right button and I could see the option Send to Terminal but the submenu  is empty.

I am using MacOS with the newest version updated.

Regards,

Fabio

**Comment by holgerbrandl** [comment]
Hey, somehow this ticket slippe through. Sorry for the delay. You should see a menu like
![image](https://cloud.githubusercontent.com/assets/200952/23543612/3b2efef2-fff3-11e6-81f5-6ac52e82db27.png)

What file type are you working with?

**Comment by holgerbrandl** [comment]
I've found the mistake and fixed it in 8d51799. Now the menu is available for all file-types. I've deployed it already to the plugins repository, so it will be shipped to users after Jetbrains is done with reviewing it.
